// Deterministic recommendation pipeline: hard filters -> scoring -> ranking -> structured candidates.
import type { WeatherContext } from "@/lib/weather-context";
import { filterEvents } from "./filter";
import { goodAgeFit, scoreEvent } from "./score";
import { buildResponseText } from "./text";
import type { CandidateInputs, FallbackAction, PoppyCandidate, PoppyProfile, RecommendationCandidate, RecommendationConstraints } from "./types";

const MAX_RESULTS = 5;
type TrustedCandidate = PoppyCandidate & { trust_stroller_accessible?: boolean | null; trust_changing_table?: boolean | null; trust_nursing_friendly?: boolean | null; trust_parking_notes?: string | null; trust_typical_crowd_note?: string | null; trust_best_time_note?: string | null; trust_community_tips?: string[] };
function distanceLabel(miles: number | null): string | null { if (miles == null) return null; return `~${miles < 10 ? miles.toFixed(1) : Math.round(miles)} mi away`; }
function interestLabel(interest: string): string { const labels: Record<string,string>={animals:"animals",water:"water play",playgrounds:"playgrounds",arts_and_crafts:"arts & crafts",books:"books",music:"music",sports:"sports",adventure:"adventure",science:"science",trains:"trains",flying:"things that fly",food:"food"}; return labels[interest] ?? interest.replaceAll("_"," "); }
function matchedEventInterest(event: PoppyCandidate, profile: PoppyProfile): string | null { const matches: Record<string,string[]>={animals:["animal"],sports:["music_movement"],arts_and_crafts:["hands_on"],books:["storytime_experience"],music:["music_movement"],science:["hands_on"],adventure:["music_movement"],trains:["vehicle"],flying:["vehicle"]}; return profile.childInterests.find(i=>event.experience_type!=null && (matches[i]??[]).includes(event.experience_type)) ?? null; }
function eventReason(event: PoppyCandidate,miles:number|null,fit:boolean,profile:PoppyProfile):string{if(event.kind==="place"){const bits:string[]=[];if(fit&&profile.childAgeMonths!=null){const years=Math.floor(profile.childAgeMonths/12);bits.push(years>=1?`a good fit for your ${years}-year-old`:"a good fit for your little one");}const interest=matchedEventInterest(event,profile);if(interest)bits.push(`matches ${interestLabel(interest)}`);if(event.is_free)bits.push("free");if(miles!=null&&miles<=12)bits.push(`close by (~${miles<10?miles.toFixed(1):Math.round(miles)} mi)`);return bits.length?`An everyday place worth considering — ${bits.join(" · ")}.`:"An everyday place worth considering.";}const bits:string[]=[];if(fit&&profile.childAgeMonths!=null){const years=Math.floor(profile.childAgeMonths/12);bits.push(years>=1?`great for your ${years}-year-old`:"great for your little one");}const interest=matchedEventInterest(event,profile);if(interest)bits.push(`matches ${interestLabel(interest)}`);if(event.is_free)bits.push("free");if(miles!=null&&miles<=12)bits.push(`close by (~${miles<10?miles.toFixed(1):Math.round(miles)} mi)`);if(bits.length===0)return"Happening soon and worth a look.";return`Looks ${bits.join(" · ")}.`;}

// Phase A: events and places both flow through this ONE mapping — kind
// decides time/href/reason shape, nothing branches on a separate place
// input array. There is exactly one place model (the honest candidate
// view); see filter.ts's per-kind eligibility for how places qualify at
// all without a fabricated occurrence time.
export function recommend(inputs:CandidateInputs,constraints:RecommendationConstraints,profile:PoppyProfile,origin:{lat:number;lng:number}|null,weather:WeatherContext|null,now:Date,maxResults=MAX_RESULTS):{candidates:RecommendationCandidate[];droppedCount:number}{
 const eventsFiltered=filterEvents(inputs.events,constraints,origin,now);
 const eventCandidates:RecommendationCandidate[]=eventsFiltered.kept.map(({event,miles})=>{const trusted=event as TrustedCandidate;const fit=goodAgeFit(profile.childAgeMonths,event.age_min_months,event.age_max_months);const isPlace=event.kind==="place";return{type:isPlace?"place":"event",id:event.id,title:event.title,description:event.description,address:event.address??event.venue,distanceMiles:miles,driveMinutes:null,distanceLabel:distanceLabel(miles),startsAt:isPlace?null:(event.time_unknown?null:event.starts_at),endsAt:isPlace?null:event.ends_at,price:event.cost,isFree:event.is_free,isOutdoor:event.is_outdoor,ageMinMonths:event.age_min_months,ageMaxMonths:event.age_max_months,goodAgeFit:fit,reason:eventReason(event,miles,fit,profile),href:isPlace?`/places/${event.place_id ?? event.id}/propose`:`/events/${event.id}`,lastVerifiedAt:event.last_verified_at,score:scoreEvent(event,miles,constraints,profile,weather),whatToBring:event.what_to_bring??[],strollerAccessible:trusted.trust_stroller_accessible??null,changingTable:trusted.trust_changing_table??null,nursingFriendly:trusted.trust_nursing_friendly??null,parkingNotes:trusted.trust_parking_notes??null,typicalCrowdNote:trusted.trust_typical_crowd_note??null,bestTimeNote:trusted.trust_best_time_note??null,registrationRequired:event.registration_required===true,communityTips:trusted.trust_community_tips??[]};});
 const ranked=eventCandidates.sort((a,b)=>b.score-a.score).slice(0,Math.max(MAX_RESULTS,maxResults)); return{candidates:ranked,droppedCount:eventsFiltered.droppedCount};
}

export function buildFallbacks(constraints:RecommendationConstraints):FallbackAction[]{const actions:FallbackAction[]=[];if(constraints.maxMiles!=null)actions.push({key:"farther",label:"Search farther",patch:{maxMiles:Math.min(60,Math.round((constraints.maxMiles??15)*2))}});if(constraints.indoor!=="indoor")actions.push({key:"indoors",label:"Try indoors",patch:{indoor:"indoor",indoorExplicit:true,mood:"indoor"}});if(constraints.indoor!=="outdoor")actions.push({key:"outdoors",label:"Try outdoors",patch:{indoor:"outdoor",indoorExplicit:true,mood:"outdoor"}});if(constraints.timeframe!=="any")actions.push({key:"anyday",label:"Try another day",patch:{timeframe:"any"}});if(constraints.timeOfDay!=="any")actions.push({key:"anytime",label:"Try another time",patch:{timeOfDay:"any"}});if(constraints.maxPriceDollars!=null)actions.push({key:"more_budget",label:"Raise the budget",patch:{maxPriceDollars:null,budget:"any"}});actions.push({key:"anything",label:"Show anything nearby",patch:{mood:"all",indoor:"either",indoorExplicit:false,budget:"any",maxPriceDollars:null}});return actions;}
export { buildResponseText };
