// Candidate scoring. Hard constraints are applied before this module runs.
import { isFreeCost } from "@/lib/cost";
import { isGoodAgeFit } from "@/lib/ageFit";
import { weatherScore, type WeatherContext } from "@/lib/weather-context";
import type { FeedEvent, Place } from "@/types";
import type { PoppyProfile, RecommendationConstraints } from "./types";
function ageScore(min:number|null,max:number|null,age:number|null):number{if(age==null)return 0;const lo=min??0,hi=max??144;if(age>=lo&&age<=hi)return 40;if(age>=lo-6&&age<=hi+6)return 12;return-25;}
function distanceScore(miles:number|null):number{return miles==null?0:Math.max(0,25-miles*1.1);}
function freshnessScore(value:string|null):number{if(!value)return-4;const t=new Date(value).getTime();if(!Number.isFinite(t))return-4;const days=Math.max(0,(Date.now()-t)/86400000);if(days<=1)return 8;if(days<=7)return 5;if(days<=30)return 2;if(days<=90)return-3;return-8;}
const INTEREST_TO_PLACE_TAGS:Record<string,string[]>={animals:["animals"],water:["water_play"],sports:["active_play","playground"],playgrounds:["playground"],arts_and_crafts:["arts_learning"],books:["storytime"],music:["arts_learning"],science:["arts_learning"],adventure:["active_play","outdoor"],trains:[],flying:[],food:[]};
const INTEREST_TO_EVENT_EXPERIENCE:Record<string,string[]>={animals:["animal"],water:[],sports:["music_movement"],playgrounds:[],arts_and_crafts:["hands_on"],books:["storytime_experience"],music:["music_movement"],science:["hands_on"],adventure:["music_movement"],trains:["vehicle"],flying:["vehicle"],food:[]};
function interestBoostPlace(place:Place,profile:PoppyProfile):number{let boost=0;for(const interest of new Set(profile.childInterests)){if((INTEREST_TO_PLACE_TAGS[interest]??[]).some(t=>place.category_tags.includes(t)))boost+=10;}if(profile.preferredCategories.some(c=>place.category_tags.includes(c)))boost+=8;if(place.place_type&&profile.preferredPlaceTypes.includes(place.place_type))boost+=8;return boost;}
function interestBoostEvent(event:FeedEvent,profile:PoppyProfile):number{let boost=0;for(const interest of new Set(profile.childInterests)){if(event.experience_type&&(INTEREST_TO_EVENT_EXPERIENCE[interest]??[]).includes(event.experience_type))boost+=10;}return boost;}
function indoorPrefScore(isOutdoor:boolean|null,c:RecommendationConstraints,profile:PoppyProfile):number{if(c.indoorExplicit||isOutdoor==null)return 0;const pref=profile.indoorPreference;if(pref==="either")return 0;return(pref==="outdoor"?isOutdoor===true:isOutdoor===false)?8:-6;}
function budgetSignalFromNote(note:string|null):"free"|"budget"|"any"{const s=(note??"").toLowerCase();if(/free|no cost|no money/.test(s))return"free";if(/cheap|budget|low.?cost|affordable/.test(s))return"budget";return"any";}
function budgetScore(isFree:boolean,c:RecommendationConstraints,profile:PoppyProfile):number{const effective=c.budget!=="any"?c.budget:budgetSignalFromNote(profile.familyBudgetNote);if(effective==="free")return isFree?15:-4;if(effective==="budget")return isFree?8:0;return 0;}
const EXPERIENCE_BOOSTS:Record<string,number>={community_helper:24,animal:22,vehicle:22,storytime_experience:20,sensory:18,hands_on:18,music_movement:15,general:0};
export function scorePlace(place:Place,miles:number|null,c:RecommendationConstraints,profile:PoppyProfile,weather:WeatherContext|null):number{let score=20;score+=ageScore(place.age_min_months,place.age_max_months,profile.childAgeMonths);score+=distanceScore(miles);score+=freshnessScore(place.last_verified_at);score+=weatherScore(weather,place.is_outdoor);score+=interestBoostPlace(place,profile);score+=indoorPrefScore(place.is_outdoor,c,profile);score+=budgetScore(isFreeCost(place.price_note),c,profile);if(c.mood!=="all")score+=20;if(place.toddler_notes)score+=6;if(place.stroller_accessible)score+=3;if(place.has_changing_table)score+=4;if(place.restrooms)score+=2;if(place.nursing_friendly)score+=2;if(place.parking_notes)score+=1;return score;}
export function scoreEvent(event:FeedEvent,miles:number|null,c:RecommendationConstraints,profile:PoppyProfile,weather:WeatherContext|null):number{let score=0;if(event.content_status==="keep")score+=20;if(event.geography_tier==="pasco")score+=12;else if(event.geography_tier==="tampa")score+=4;score+=ageScore(event.age_min_months,event.age_max_months,profile.childAgeMonths);score+=distanceScore(miles);score+=freshnessScore(event.last_verified_at);score+=weatherScore(weather,event.is_outdoor);score+=EXPERIENCE_BOOSTS[event.experience_type??"general"]??0;score+=interestBoostEvent(event,profile);score+=indoorPrefScore(event.is_outdoor,c,profile);score+=budgetScore(event.is_free,c,profile);if(c.mood!=="all")score+=20;if(event.registration_required)score-=2;return score;}
export function goodAgeFit(childAgeMonths:number|null,min:number|null,max:number|null):boolean{return isGoodAgeFit(childAgeMonths,min,max);}
