import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const MODEL=Deno.env.get("GEMINI_MODEL")??"gemini-3.5-flash-lite";
const URL=`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
// Raised from the original controlled-canary limit of 10 to 50 places/run
// (2026-08-27, user-authorized) - still bounded (10 Gemini batches/run,
// ~30-60s runtime), not a full-backlog drain.
const PLACES_PER_RUN=50;
const SYSTEM=`Extract facility facts from ONLY the supplied public place description. Never infer. For every non-null claim provide an exact quote copied from the description. If unsupported, use null and empty evidence. Return ONLY a JSON array: {"id":"<id>","has_changing_table":true|false|null,"nursing_friendly":true|false|null,"stroller_accessible":true|false|null,"quiet_or_sensory_friendly":true|false|null,"what_to_bring":["item"],"price_note":"string"|null,"parking_notes":"string"|null,"evidence":{"has_changing_table":"quote","nursing_friendly":"quote","stroller_accessible":"quote","quiet_or_sensory_friendly":"quote","what_to_bring":"quote","price_note":"quote","parking_notes":"quote"}}`;
type Row={id:string;name:string;description:string|null};
type V={id:string;has_changing_table?:unknown;nursing_friendly?:unknown;stroller_accessible?:unknown;quiet_or_sensory_friendly?:unknown;what_to_bring?:unknown;price_note?:unknown;parking_notes?:unknown;evidence?:Record<string,unknown>};
const bool=(x:unknown)=>typeof x==='boolean'?x:null;
const str=(x:unknown)=>typeof x==='string'&&x.trim()?x.trim().slice(0,300):null;
const arr=(x:unknown)=>Array.isArray(x)?x.filter(y=>typeof y==='string'&&y.trim()).map(y=>y.trim().slice(0,60)).slice(0,12):[];
const ev=(x:unknown)=>typeof x==='string'?x.trim().slice(0,500):'';
function norm(s:string){return s.normalize('NFKC').replace(/[""„‟]/g,'"').replace(/['''‚‛]/g,"'").replace(/[–—−]/g,'-').replace(/ /g,' ').replace(/\s+/g,' ').trim().toLowerCase();}
function supported(description:string|null,quote:string){const d=norm(description??'');const q=norm(quote);return q.length>=8&&d.includes(q);}
async function key(){const {data,error}=await db.rpc('get_gemini_key');if(error||typeof data!=='string'||!data)throw new Error('gemini_key lookup failed');return data;}
async function gemini(rows:Row[],k:string){const payload=rows.map(r=>({id:r.id,name:r.name??'',description:(r.description??'').slice(0,2000)}));const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':k},body:JSON.stringify({contents:[{parts:[{text:`${SYSTEM}\nPLACES:\n${JSON.stringify(payload)}`}]}],generationConfig:{temperature:0,responseMimeType:'application/json',thinkingConfig:{thinkingLevel:'minimal'}}}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Gemini ${r.status}: ${(await r.text()).slice(0,300)}`);const j=await r.json();const t=j?.candidates?.[0]?.content?.parts?.[0]?.text??'[]';const p=JSON.parse(t);const m=new Map<string,V>();for(const x of Array.isArray(p)?p:[])if(x?.id)m.set(String(x.id),x);return m;}
async function writePlace(r:Row,v:V){const fields:any={};const evidence:any={};const rejected:string[]=[];const specs:any=[['has_changing_table',bool(v.has_changing_table)],['nursing_friendly',bool(v.nursing_friendly)],['stroller_accessible',bool(v.stroller_accessible)],['quiet_or_sensory_friendly',bool(v.quiet_or_sensory_friendly)],['what_to_bring',arr(v.what_to_bring)],['price_note',str(v.price_note)],['parking_notes',str(v.parking_notes)]];
for(const [name,value] of specs){if(value===null||value===false&&name==='what_to_bring')continue;const quote=ev(v.evidence?.[name]);if((name==='what_to_bring'&&value.length===0)||!quote||!supported(r.description,quote)){if(value!==null&&(name!=='what_to_bring'||value.length>0))rejected.push(name);continue;}if(name==='what_to_bring')fields[name]=value;else fields[name]=value;evidence[name]=quote;}
const acceptedCount=Object.keys(evidence).length;const status=acceptedCount>0&&rejected.length===0?'verified':rejected.length>0?'needs_review':'unverified';
const body:any={...fields,llm_enrichment_evidence:evidence,llm_enrichment_provenance:{verified_ai:evidence},llm_last_revalidation:{accepted:evidence,rejected,verified:status==='verified'},llm_verification_status:status};
if(acceptedCount>0){body.llm_enriched_at=new Date().toISOString();body.llm_model=MODEL;}if(status==='verified')body.llm_verified_at=new Date().toISOString();
// Fill gaps only: never overwrite a non-null scalar and never replace a non-empty text field.
const {data:current,error:ce}=await db.from('places').select('has_changing_table,nursing_friendly,stroller_accessible,quiet_or_sensory_friendly,price_note,parking_notes,llm_enrichment_evidence,llm_enrichment_provenance').eq('id',r.id).eq('active',true).single();if(ce)throw ce;
for(const n of ['has_changing_table','nursing_friendly','stroller_accessible','quiet_or_sensory_friendly'])if(current[n]!==null)delete body[n];
if(current.price_note)delete body.price_note;if(current.parking_notes)delete body.parking_notes;
body.llm_enrichment_evidence={...(current.llm_enrichment_evidence??{}),...evidence};body.llm_enrichment_provenance={...(current.llm_enrichment_provenance??{}),verified_ai:evidence};
const {error}=await db.from('places').update(body).eq('id',r.id).eq('active',true);if(error)throw error;return {accepted:Object.keys(evidence),rejected,status};}
Deno.serve(async req=>{if(req.method!=='POST')return Response.json({error:'POST required'},{status:405});const secret=req.headers.get('x-cron-secret');if(!secret)return Response.json({error:'Unauthorized'},{status:401});const {data:valid}=await db.rpc('validate_community_cron_secret',{provided_secret:secret});if(valid!==true)return Response.json({error:'Unauthorized'},{status:401});let k:string;try{k=await key();}catch(e){return Response.json({error:String(e)},{status:500});}const {data,error}=await db.rpc('get_places_for_revalidation',{p_limit:PLACES_PER_RUN});if(error)return Response.json({error:error.message},{status:500});const q=(data??[])as Row[];let enriched=0,skipped=0,gemini_failed_batches=0,missing_verdicts=0,write_failures=0,claims_accepted=0,claims_rejected=0;let last_error='';for(let i=0;i<q.length;i+=5){const b=q.slice(i,i+5);let vs:Map<string,V>;try{vs=await gemini(b,k);}catch(e){gemini_failed_batches++;skipped+=b.length;last_error=String(e instanceof Error?e.message:e).slice(0,400);continue;}for(const r of b){const v=vs.get(r.id);if(!v){missing_verdicts++;skipped++;continue;}try{const x=await writePlace(r,v);claims_accepted+=x.accepted.length;claims_rejected+=x.rejected.length;if(x.status==='verified')enriched++;else if(x.status==='needs_review')skipped++;else skipped++;}catch(e){write_failures++;skipped++;last_error=String(e instanceof Error?e.message:e).slice(0,400);}}if(i+5<q.length)await new Promise(r=>setTimeout(r,3000));}
return Response.json({ok:true,model:MODEL,queue_pulled:q.length,enriched,skipped,claims_accepted,claims_rejected,gemini_failed_batches,missing_verdicts,write_failures,last_error,runtime_ms:0});});
