import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const bad=/\b(adults? only|18\+|21\+|teen|teens|senior|date night|parents? night out|ladies night|happy hour|crime|police|murder|road closure|paving|permit|zoning|construction)\b/i;
const kid=/\b(kids?|children|toddler|baby|babies|preschool|family|families|mommy|parent[- ]child|sensory|storytime|story time|play|craft|music|dance|open house|workshop|festival|fair|market|concert|movie|celebration|program|class)\b/i;
const dateRe=/\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?)\s+\d{1,2}(?:,\s*20\d{2})?\b/i;
const timeRe=/\b(?:[1-9]|1[0-2])(?::[0-5]\d)?\s*(?:am|pm)\b/i;
function clean(s:string){return s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#8217;|&#x2019;/gi,"’").replace(/&#8211;|&#x2013;/gi,"–").replace(/&bull;/gi,"•").replace(/\s+/g," ").trim()}
function toDate(raw:string){if(!raw)return null;const x=/\b20\d{2}\b/.test(raw)?raw:`${raw}, 2026`;const d=new Date(x);return Number.isNaN(d.getTime())?null:d.toISOString()}
function score(s:string){let n=35;if(kid.test(s))n+=30;if(/free|complimentary|drop[- ]in/i.test(s))n+=10;if(bad.test(s))n-=80;return Math.max(0,Math.min(99,n))}
function structured(html:string,url:string){const out:any[]=[];for(const tag of html.match(/<script[^>]*type=[\"']application\/ld\+json[\"'][^>]*>[\s\S]*?<\/script>/gi)||[]){try{const raw=tag.replace(/^<script[^>]*>|<\/script>$/gi,"");const walk=(v:any)=>{if(!v)return;if(Array.isArray(v)){v.forEach(walk);return}if(typeof v!=="object")return;const t=Array.isArray(v["@type"])?v["@type"]:[v["@type"]];if(t.some((x:any)=>String(x).toLowerCase()==="event")&&typeof v.name==="string"&&!bad.test(v.name)){const title=clean(v.name);const start=String(v.startDate||v.endDate||"");const loc=typeof v.location==="string"?v.location:(v.location?.name||v.location?.address?.streetAddress||"");const event_date=toDate(start);if(event_date&&title&&!dateRe.test(title)&&!/^\d/.test(title))out.push({event_title:title.slice(0,180),event_date,location_text:clean(String(loc)).slice(0,300),signal_text:clean([title,start,loc].join(" — ")).slice(0,1200),source_url:url,confidence:Math.min(.99,.60+score(title)/180)})}Object.values(v).forEach(walk)};walk(JSON.parse(raw))}catch{}}return out}
function anchorEvents(html:string,url:string){const anchors:any[]=[];const ar=/<a\b[^>]*href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=ar.exec(html))){const label=clean(m[2]);if(!label||label.length<5||label.length>180)continue;try{const u=new URL(m[1],url);if(/\/event\//i.test(u.pathname)||(/event/i.test(u.pathname)&&kid.test(label)))anchors.push({label,url:u.toString(),pos:m.index})}catch{}}const out:any[]=[];for(const a of anchors){const w=clean(html.slice(Math.max(0,a.pos-1800),Math.min(html.length,a.pos+1800)));const dm=w.match(dateRe);if(!dm)continue;const tm=w.match(timeRe);const title=a.label.replace(/^«\s*All Events\s*/i,"").replace(/^Series:\s*/i,"").trim();if(!title||dateRe.test(title)||/^\d/.test(title)||bad.test(title))continue;const sc=score(title+" "+w);if(sc<45)continue;const event_date=toDate(dm[0]+(tm?" "+tm[0]:""));if(event_date)out.push({event_title:title,event_date,signal_text:w.slice(0,1200),source_url:a.url,confidence:Math.min(.99,.50+sc/180)})}return out}
function fallback(html:string,url:string){const out:any[]=[];const blocks=(html.match(/<(?:h1|h2|h3|h4|h5|article|li|p)[^>]*>[\s\S]*?<\/(?:h1|h2|h3|h4|h5|article|li|p)>/gi)||[]).map(clean);for(let i=0;i<blocks.length;i++){const w=blocks.slice(Math.max(0,i-2),i+3).join(" ");const dm=w.match(dateRe);if(!dm||!kid.test(w)||bad.test(w))continue;const title=blocks[i];if(!title||title.length>140||dateRe.test(title)||/^\d/.test(title))continue;const event_date=toDate(dm[0]+((w.match(timeRe)||[])[0]||""));if(event_date)out.push({event_title:title,event_date,signal_text:w.slice(0,1200),source_url:url,confidence:.55})}return out}
function parse(html:string,url:string){const a=structured(html,url);const b=a.length?[]:anchorEvents(html,url);const c=a.length||b.length?[]:fallback(html,url);const all=[...a,...b,...c].filter(x=>x.event_title&&x.event_date);return [...new Map(all.map(x=>[x.source_url+"|"+x.event_title+"|"+x.event_date,x])).values()].slice(0,40)}
function links(html:string,base:string){const out=new Set<string>();const r=/<a\b[^>]*href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=r.exec(html))&&out.size<10){const label=clean(m[2]);if(!/event|calendar|kids|children|family|toddler|storytime|program|class/i.test(label+m[1]))continue;try{const u=new URL(m[1],base);if(u.protocol.startsWith("http"))out.add(u.toString())}catch{}}return [...out]}
async function fetchWithTimeout(url:string,ms=12000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{signal:c.signal,headers:{"User-Agent":"MommasMeetup/1.0 community-signal-discovery"}})}finally{clearTimeout(t)}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out:R[]=[];let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function organizer(s:any){if(s.organizer_id)return s.organizer_id;try{const website=new URL(s.source_url).origin;const {data:e}=await db.from("known_organizers").select("id").eq("website",website).limit(1).maybeSingle();if(e?.id){await db.from("content_sources").update({organizer_id:e.id}).eq("id",s.id);return e.id}const {data:o}=await db.from("known_organizers").insert({name:s.name,organizer_type:"community",website,priority:Math.max(50,s.source_priority||50),reliability_score:s.reliability_score||50,active:true}).select("id").single();return o?.id||null}catch{return null}}
Deno.serve(async req=>{if(req.method!=="POST")return Response.json({error:"POST required"},{status:405});const secret=req.headers.get("x-cron-secret");if(!secret)return Response.json({error:"Unauthorized"},{status:401});const {data:valid}=await db.rpc("validate_community_cron_secret",{provided_secret:secret});if(valid!==true)return Response.json({error:"Unauthorized"},{status:401});const started=new Date().toISOString();const {data:a}=await db.from("community_signal_run_audit").insert({function_name:"discover-community-signals-v2",started_at:started,status:"running",sources_attempted:0,sources_succeeded:0,signals_found:0,signals_saved:0,sources_added:0,errors:0}).select("id").single();const {data:sources,error}=await db.from("content_sources").select("id,name,source_url,source_priority,reliability_score,organizer_id,last_attempted_at").eq("active",true).in("discovery_channel",["community","organizer"]).order("last_attempted_at",{ascending:true,nullsFirst:true}).order("source_priority",{ascending:false}).limit(20);if(error){if(a?.id)await db.from("community_signal_run_audit").update({finished_at:new Date().toISOString(),status:"failed",errors:1,error_message:error.message}).eq("id",a.id);return Response.json({error:error.message},{status:500})}
const fetched=await mapLimit(sources||[],5,async s=>{try{const r=await fetchWithTimeout(s.source_url);if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();return {s,html,sigs:parse(html,s.source_url),links:links(html,s.source_url),error:null}}catch(e){return {s,html:"",sigs:[],links:[],error:e instanceof Error?e.message:String(e)}}});
let okSources=0,found=0,saved=0,errors=0,added=0;const results:any[]=[];const allSignals:any[]=[];for(const x of fetched){if(x.error){errors++;await db.from("content_sources").update({last_attempted_at:new Date().toISOString(),last_error:x.error}).eq("id",x.s.id);results.push({source:x.s.name,error:x.error});continue}const org=await organizer(x.s);for(const sig of x.sigs)allSignals.push({organizer_id:org,source_url:sig.source_url,source_name:x.s.name,signal_text:sig.signal_text,event_title:sig.event_title,location_text:sig.location_text||null,event_date:sig.event_date,discovered_at:new Date().toISOString(),created_at:new Date().toISOString(),status:sig.confidence>=.84?"needs_review":"low_confidence",confidence:sig.confidence});okSources++;found+=x.sigs.length;results.push({source:x.s.name,signals_found:x.sigs.length});await db.from("content_sources").update({last_attempted_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null,last_event_count:x.sigs.length,organizer_id:org}).eq("id",x.s.id);for(const u of x.links) {const {error:ie}=await db.from("content_sources").upsert({name:`${x.s.name} — discovered`,source_type:"discovery",source_url:u,active:true,discovery_channel:"community",source_priority:Math.max(40,(x.s.source_priority||50)-10),reliability_score:45,discovery_count:0,successful_event_count:0,rejected_event_count:0},{onConflict:"source_url",ignoreDuplicates:true});if(!ie)added++}}
for(let i=0;i<allSignals.length;i+=50){const {error:ie}=await db.from("community_event_signals").upsert(allSignals.slice(i,i+50),{onConflict:"source_url,event_title,event_date",ignoreDuplicates:true});if(!ie)saved+=Math.min(50,allSignals.length-i);else errors++}
const status=errors?(okSources?"partial":"failed"):"success";if(a?.id)await db.from("community_signal_run_audit").update({finished_at:new Date().toISOString(),status,sources_attempted:(sources||[]).length,sources_succeeded:okSources,signals_found:found,signals_saved:saved,sources_added:added,errors,error_message:errors?`${errors} operation(s) failed`:null}).eq("id",a.id);return Response.json({ok:status!=="failed",status,batch_size:(sources||[]).length,concurrency:5,results,signals_found:found,signals_saved:saved,sources_added:added,errors})});