-- THIS FILE IS RETIRED. Do not run it and do not hand-edit it.
--
-- It was a hand-maintained snapshot that drifted badly from the live
-- database (missing 27 of the app's 43 tables, and missing dozens of columns
-- on the tables it did cover — e.g. `events` had 30 of its 69 live columns,
-- `places` had 30 of its 52). That drift is what caused the bootstrap bug
-- this file's removal fixes: README.md used to tell new developers to
-- "paste and run db/schema.sql", which produced a schema that didn't match
-- production.
--
-- What replaced it:
--   * supabase/migrations/  — the canonical, applied-in-order source of
--     truth for schema history going forward.
--   * db/schema-snapshot.sql — a GENERATED flattened snapshot of the live
--     schema (tables, constraints, indexes, functions, views, triggers, RLS)
--     for pasting into a fresh Supabase project's SQL editor. Regenerate it;
--     never hand-edit it. See db/README.md.
--
-- See db/README.md for the full picture of how the schema is managed.
