"use client";

import { useEffect, useOptimistic, useState, useTransition, type ReactNode } from "react";
import { rsvp } from "@/app/(app)/calendar/actions";
import OutingFeedback from "@/components/OutingFeedback";
import type { RsvpStatus } from "@/types";

const STATUS_LABELS: Record<RsvpStatus,{label:string;activeLabel:string}>={going:{label:"I'm in",activeLabel:"✓ I'm in"},maybe:{label:"Maybe",activeLabel:"✓ Maybe"},not_going:{label:"Can't go",activeLabel:"✓ Can't go"},out_sick:{label:"Out sick",activeLabel:"✓ Out sick"}};
function buttonClass(status:RsvpStatus,active:boolean){const pop="motion-safe:active:scale-95 transition-transform";if(status==="going")return active?`min-h-11 flex-1 rounded-2xl bg-emerald-600 px-5 py-3 text-base font-bold text-white shadow-sm disabled:opacity-60 ${pop}`:`min-h-11 flex-1 rounded-2xl bg-rose-600 px-5 py-3 text-base font-bold text-white shadow-sm hover:bg-rose-700 disabled:opacity-60 ${pop}`;if(status==="maybe")return active?`min-h-11 rounded-2xl border-2 border-zinc-900 bg-white px-4 py-3 text-sm font-bold text-zinc-900 disabled:opacity-60 ${pop}`:`min-h-11 rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm font-semibold text-zinc-700 hover:border-zinc-400 disabled:opacity-60 ${pop}`;return active?`min-h-11 rounded-full bg-zinc-100 px-3 py-2 text-xs font-semibold text-zinc-700 disabled:opacity-60 ${pop}`:`min-h-11 rounded-full px-3 py-2 text-xs text-zinc-400 hover:bg-zinc-50 hover:text-zinc-600 disabled:opacity-60 ${pop}`;}
export default function EventCardShell({eventId,currentStatus,currentNote,disabled=false,duringNap=false,endedAt=null,children}:{eventId:string;currentStatus:RsvpStatus|null;currentNote?:string|null;disabled?:boolean;duringNap?:boolean;endedAt?:string|null;children:ReactNode}){
 const[optimisticStatus,setOptimisticStatus]=useOptimistic(currentStatus);const[note,setNote]=useState(currentNote??"");const[isPending,startTransition]=useTransition();const[error,setError]=useState<string|null>(null);const[ended,setEnded]=useState(false);
 useEffect(()=>{if(!endedAt)return;const delay=Math.max(0,new Date(endedAt).getTime()-Date.now());const timer=window.setTimeout(()=>setEnded(true),delay);return()=>window.clearTimeout(timer);},[endedAt]);
 function handleClick(status:RsvpStatus){const next=optimisticStatus===status?null:status;setError(null);startTransition(async()=>{setOptimisticStatus(next);const result=await rsvp(eventId,next,next?note:null);if(result?.error)setError(result.error);});}
 function handleNoteBlur(){if(!optimisticStatus)return;const trimmed=note.trim();if(trimmed===(currentNote??"").trim())return;setError(null);startTransition(async()=>{const result=await rsvp(eventId,optimisticStatus,trimmed||null);if(result?.error)setError(result.error);});}
 const baseClass=disabled?"border-zinc-200 bg-zinc-50":optimisticStatus==="going"?"border-rose-200 bg-rose-50/60":"border-zinc-200 bg-white";const cardClass=`scroll-mt-4 rounded-2xl border p-4 transition-colors ${baseClass} ${duringNap?"opacity-85":""}`;
 function statusButton(status:RsvpStatus){const active=optimisticStatus===status;return <button key={status} type="button" disabled={isPending} onClick={()=>handleClick(status)} className={buttonClass(status,active)}>{active?STATUS_LABELS[status].activeLabel:STATUS_LABELS[status].label}</button>;}
 return <div id={`event-${eventId}`} className={cardClass}>{duringNap&&<p className="mb-2 rounded-lg bg-zinc-50 px-2.5 py-1.5 text-xs font-medium text-zinc-600">🌙 Overlaps nap — here if plans change</p>}{children}{disabled?<p className="mt-4 text-sm text-zinc-400">This meetup was cancelled.</p>:<><div className="mt-4 flex items-center gap-2">{statusButton("going")}{statusButton("maybe")}</div><div className="mt-1.5 flex items-center gap-1">{statusButton("not_going")}{statusButton("out_sick")}</div>{optimisticStatus&&<input type="text" value={note} onChange={e=>setNote(e.target.value.slice(0,200))} onBlur={handleNoteBlur} maxLength={200} placeholder="Add a short note (optional)" className="mt-2 w-full rounded-md border border-zinc-200 px-2.5 py-1.5 text-xs text-zinc-700 outline-none focus:border-zinc-400"/>}{error&&<p className="mt-2 text-xs text-red-600">{error}</p>}</>}<OutingFeedback eventId={eventId} visible={ended&&!disabled}/></div>;
}
