"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { FeedEvent } from "@/types";
const WEEKDAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
function eventTime(event:FeedEvent){if(event.time_unknown)return "Time to be confirmed";return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(event.starts_at));}
export default function MonthCalendar({date,events,prevHref,nextHref}:{date:Date;events:FeedEvent[];prevHref:string;nextHref:string}){
 const[query,setQuery]=useState("");const[filter,setFilter]=useState("all");
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return events.filter(e=>{if(q&&!`${e.title} ${e.venue??""} ${e.address??""}`.toLowerCase().includes(q))return false;if(filter==="free"&&!e.is_free)return false;if(filter==="indoor"&&e.is_outdoor!==false)return false;if(filter==="outdoor"&&e.is_outdoor!==true)return false;if(filter==="mine"&&e.proposed_by_group==null)return false;return true;}).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());},[events,query,filter]);
 const year=date.getFullYear(),month=date.getMonth(),firstOfMonth=new Date(year,month,1),daysInMonth=new Date(year,month+1,0).getDate(),startWeekday=firstOfMonth.getDay(),today=new Date(),isCurrentMonth=today.getFullYear()===year&&today.getMonth()===month;
 const eventsByDay=new Map<number,FeedEvent[]>();for(const event of filtered){const day=new Date(event.starts_at).getDate();eventsByDay.set(day,[...(eventsByDay.get(day)??[]),event]);}
 const cells:(number|null)[]=[...Array(startWeekday).fill(null),...Array.from({length:daysInMonth},(_,i)=>i+1)];while(cells.length%7!==0)cells.push(null);
 const monthLabel=firstOfMonth.toLocaleDateString(undefined,{month:"long",year:"numeric"});
 return <div className="w-full max-w-2xl">
  <div className="mb-4 flex items-center justify-between rounded-2xl border border-zinc-200 bg-white px-3 py-2 shadow-sm sm:border-0 sm:bg-transparent sm:px-0 sm:py-0 sm:shadow-none"><Link href={prevHref} className="inline-flex min-h-11 items-center rounded-xl px-2 text-sm font-semibold text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900">← Prev</Link><h2 className="font-display text-xl font-bold text-zinc-950">{monthLabel}</h2><Link href={nextHref} className="inline-flex min-h-11 items-center rounded-xl px-2 text-sm font-semibold text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900">Next →</Link></div>
  <div className="mb-5 rounded-2xl border border-zinc-200 bg-white p-3 shadow-sm"><label htmlFor="calendar-search" className="sr-only">Search calendar</label><input id="calendar-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your plans…" className="w-full rounded-xl border border-zinc-200 px-3 py-2.5 text-sm outline-none focus:border-rose-400 focus:ring-2 focus:ring-rose-100"/><div className="mt-3 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Calendar filters">{[{id:"all",label:"All"},{id:"free",label:"Free"},{id:"indoor",label:"Indoor"},{id:"outdoor",label:"Outdoor"},{id:"mine",label:"Proposed"}].map(f=><button key={f.id} type="button" role="tab" aria-selected={filter===f.id} onClick={()=>setFilter(f.id)} className={filter===f.id?"min-h-10 shrink-0 rounded-full bg-zinc-900 px-3 py-2 text-xs font-bold text-white":"min-h-10 shrink-0 rounded-full border border-zinc-200 bg-white px-3 py-2 text-xs font-semibold text-zinc-700"}>{f.label}</button>)}</div><p className="mt-2 text-xs text-zinc-500">{filtered.length} planned option{filtered.length===1?"":"s"} · Calendar shows your plans; use Today/Poppy for discovery.</p></div>
  <div className="sm:hidden">{filtered.length===0?<p className="rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 p-5 text-sm text-zinc-600">Nothing matches these filters.</p>:<div className="flex flex-col gap-2">{filtered.map(event=>{const d=new Date(event.starts_at);return <Link key={event.id} href={`#event-${event.id}`} className="flex min-h-[72px] items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-3 shadow-sm transition active:scale-[0.99] hover:border-rose-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500"><div className="flex h-12 w-12 shrink-0 flex-col items-center justify-center rounded-xl bg-rose-50 text-rose-700"><span className="text-[10px] font-bold uppercase">{d.toLocaleDateString(undefined,{weekday:"short"})}</span><span className="text-lg font-bold leading-none">{d.getDate()}</span></div><div className="min-w-0 flex-1"><div className={event.status==="cancelled"?"truncate text-sm font-bold text-zinc-400 line-through":"truncate text-sm font-bold text-zinc-900"}>{event.title}</div><div className="mt-1 text-xs font-semibold text-zinc-500">{eventTime(event)}{event.venue?` · ${event.venue}`:""}{event.is_free?" · Free":""}</div></div><span aria-hidden="true" className="shrink-0 text-lg text-rose-600">→</span></Link>})}</div>}</div>
  <div className="hidden sm:block"><div className="grid grid-cols-7 gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 text-sm shadow-sm">{WEEKDAYS.map(day=><div key={day} className="bg-zinc-50 px-2 py-2 text-center text-xs font-bold text-zinc-500">{day}</div>)}{cells.map((day,i)=>{const dayEvents=day!==null?(eventsByDay.get(day)??[]):[];return <div key={i} className={`min-h-20 bg-white px-2 py-2 ${day===null?"bg-zinc-50":""}`}>{day!==null&&<><span className={isCurrentMonth&&day===today.getDate()?"inline-flex h-7 w-7 items-center justify-center rounded-full bg-zinc-900 text-xs font-bold text-white":"inline-flex h-7 w-7 items-center justify-center text-xs font-semibold text-zinc-700"}>{day}</span><div className="mt-1 flex flex-col gap-0.5">{dayEvents.slice(0,2).map(event=><Link key={event.id} href={`#event-${event.id}`} className={event.status==="cancelled"?"truncate rounded-lg bg-zinc-100 px-1.5 py-1 text-left text-[11px] text-zinc-400 line-through hover:bg-zinc-200":"truncate rounded-lg bg-rose-50 px-1.5 py-1 text-left text-[11px] font-semibold text-rose-800 hover:bg-rose-100"} title={event.title}>{event.title}</Link>)}{dayEvents.length>2&&<span className="text-[11px] font-semibold text-zinc-400">+{dayEvents.length-2} more</span>}</div></>}</div>})}</div>{filtered.length===0&&<p className="mt-4 text-sm text-zinc-500">Nothing matches these filters.</p>}</div>
 </div>;
}
